apiVersion: v1
kind: Service
metadata:
  name: {{ include "demory.fullname" . }}
  labels:
    {{- include "demory.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    {{- include "demory.selectorLabels" . | nindent 4 }}
