apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "demory.fullname" . }}
  labels:
    {{- include "demory.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "demory.fullname" . }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "demory.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "demory.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "demory.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DEMORY_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DEMORY_NODE_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DEMORY_PORT
              value: "{{ .Values.application.port }}"
            - name: DEMORY_DISCOVERY_STRATEGY
              value: {{ .Values.application.discoveryStrategy }}
            - name: DEMORY_KUBERNETES_SERVICE
              value: {{ include "demory.fullname" . }}
            - name: DEMORY_KUBERNETES_NAMESPACE
              value: {{ .Release.Namespace }}
          ports:
            - name: tcp
              containerPort: {{ .Values.application.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: tcp
          readinessProbe:
            tcpSocket:
              port: tcp
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
