apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jaeger.fullname" . }}
data:
  jaeger-ui.json: |
    {
      "monitor": {
        "menuEnabled": true
      },
      "dependencies": {
        "menuEnabled": true
      }
    }